---
title: "R Notebook"
output: html_notebook
---



```{r}
library(airtabler)

spacedogs <- 
  airtable(
    base = "", 
    tables = c("Dogs", "FLIGHTS")
  )
```

```{r}
dogs <- 
  spacedogs$Dogs$select()
```

```{r}
library(tidyverse)

space_dogs <- dogs %>% 
  # The Fate column seems to either say "Survived" or "Died <DATE>", so we make
  # a new binary version of the Fate column that is "Survived" if the dog
  # survived and "Died" otherwise
  mutate(Fate_binary = ifelse(Fate == "Survived", "Survived", "Died")) %>% 
  # The data lists the dates of each flight, separated by a comma. To convert
  # that to a number, we do a little trick: count the number of commas in the
  # cell and add 1 (if there were 2 flights, there would be 1 comma, etc.)
  mutate(Flights_num = str_count(Flights, ",") + 1) %>% 
  select(-Flights, -id, -Notes)

space_dogs

write_csv(space_dogs, "space_dogs.csv")
```
```{r}
space_dogs_summarized <- space_dogs %>% 
  group_by(Fate_binary, Gender) %>% 
  summarize(total_dogs = n(),
            total_flights = sum(Flights_num))

space_dogs_summarized

write_csv(space_dogs_summarized, "space_dogs_summarized.csv")
```

```{r}
ugly_plot <- ggplot(data = space_dogs_summarized, 
                    mapping = aes(x = Fate_binary, y = total_flights, color = Gender)) +
  geom_pointrange(aes(ymin = 0, ymax = total_flights), size = 2, 
                  position = position_dodge(width = 0.5)) +
  theme_gray() +
  theme(
    plot.background = element_rect(fill = "orange"),
    legend.margin = margin(20,1,50,1),
    legend.background = element_rect(fill = "yellow"),
    panel.background = element_rect(fill = "black")
  )

ugly_plot
```

